// src/styles/global.js
import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  topContainer: {
    flex: 1,
    backgroundColor: 'white',
  },
  container: {
    flex: 1,
    paddingHorizontal: 8,
    backgroundColor: 'white',
  },
  list: {
    marginTop: 10,
  },
  itemContainer: {
    flex: 1,
    margin: 5,
    borderRadius: 8,
    backgroundColor: 'white',
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 2,
    elevation: 5,
  },
  imageContainer: {
    width: '100%',
    height: 250,
    resizeMode: 'cover',
    borderRadius: 8,
    overflow: 'hidden',
  },
  title: {
    fontSize: 12,
    fontWeight: 'medium',
    color: 'black',
    paddingVertical: 10,
    width: '90%',
    marginLeft: 5,
  },
  language: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: 16,
    textAlign: 'center',
  },
  priceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 5,
  },
  currencyText: {
    fontSize: 10,
    lineHeight: 16,
    fontWeight: 'bold',
    color: '#E70028',
    alignSelf: 'flex-end',
  },
  priceText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#E70028',
    paddingLeft: 2,
  },
  comparePriceText: {
    fontSize: 12,
    fontWeight: 'black',
    color: 'black',
    textDecorationLine: 'line-through',
    alignSelf: 'flex-end',
    paddingLeft: 5,
  },
  offerPriceContainer: {
    flexDirection: 'row',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  offerContainer: {
    flexDirection: 'row',
    width: '90%',
    alignItems: 'center',
    padding: 2,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: '#E70028',
    borderStyle: 'dashed',
    backgroundColor: '#FFE6E7',
    marginVertical: 10,
    marginLeft: 5,
  },
  offerText: {
    fontSize: 8,
    fontWeight: 'bold',
    color: 'black',
    paddingLeft: 5,
  },
  cartIcon: {
    height: 25,
    width: 25,
    alignSelf: 'center',
    marginRight: 16,
  },
  totalProducts: {
    fontSize: 12,
    fontWeight: 'bold',
    color: 'black',
    marginTop: 10,
    alignSelf: 'flex-end',
  },
  offerIcon: {
    height: 14,
    width: 14,
    alignSelf: 'center',
    marginLeft: 5,
    resizeMode: 'cover',
  },
  cartCount: {
    backgroundColor: 'red',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 5,
    position: 'absolute',
    right: 10,
  },
  cartCountText: {
    color: 'white',
    fontSize: 12,
  },
  headerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
  },
  titleText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: 'black',
  },
  shoppingIconContainer: {
    alignSelf: 'center',
    right: 5,
    bottom: 100,
    position: 'absolute',
    height: 45,
    width: 45,
    borderRadius: 25,
    backgroundColor: 'white',
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 2,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  shoppingIcon: {
    height: 20,
    width: 20,
    resizeMode: 'contain',
  },
  modalBackground: {
    flex: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  closeButton: {
    alignSelf: 'center',
    top: 60,
    right: 16,
    bottom: 100,
    position: 'absolute',
    height: 45,
    width: 45,
    borderRadius: 25,
    backgroundColor: 'white',
    shadowColor: 'black',
    shadowOpacity: 0.26,
    shadowOffset: {width: 0, height: 2},
    shadowRadius: 2,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeButtonText: {
    fontSize: 30,
    lineHeight: 30,
    fontWeight: 'bold',
    color: 'black',
    transform: [{rotate: '45deg'}],
  },
  imageItem: {
    width: 400,
    height: 500,
    resizeMode: 'contain',
    alignSelf: 'center',
  },
  animatedProduct: {
    position: 'absolute',
    width: 100,
    height: 200,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 25,
  },
  productContainer: {
    width: '50%',
  },
});

export default styles;
